### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by victoriagnatiuk** [G05PE/Practica-1#7]
Implementar interfaz gráfica. La aplicación debe permitir variar los parámetros
interactivamente. Los parámetros predeterminados son: tamaño de la población (100),
número de generaciones (100), porcentaje de cruces (60%), porcentaje de mutaciones (5%),
precisión o valor de error para la discretización del intervalo (0.001) y posibilidad de
seleccionar porcentaje de elitismo.

**Comment by K43M1S** [comment]
No me funciona la GUI, el 2DPanel me da problema y no me importa las librerías, habría que probar en otros ordenadores que no sea el tuyo.
